language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failure:
    - rust: nightly
  fast_finish: true

cache: cargo
os: linux
services:
  - docker

before_install:
- docker pull selenium/standalone-chrome:3.141.59-zinc
- docker run --rm -d --network host --name selenium-server -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-zinc
- docker pull stevepryde/webappdemo:latest
- docker run -d -p 8000:80 stevepryde/webappdemo:latest
- docker ps -a
