language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failure:
    - rust: nightly
  fast_finish: true

cache: cargo
os: linux
services:
  - docker

before_install:
- docker-compose up -d --build
- docker ps -a

script:
  - cargo test --verbose --features=blocking -- --test-threads=1
