[package]
name = "thirtyfour"
description = "Selenium webdriver client for Rust, inspired by the python selenium library"
version = "0.1.0"
authors = ["Steve Pryde <steve@stevepryde.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/stevepryde/thirtyfour"
repository = "https://github.com/stevepryde/thirtyfour"
keywords = ["selenium", "webdriver", "testing", "test"]
categories = ["development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.0-alpha.2"
serde_json = "1.0"
log = "0.4"
urlparse = "0.7.3"
rustc_version_runtime = "0.1.5"
base64 = "0.11.0"
