[package]
name = "thirtyfour"
version = "0.2.4"
authors = ["Steve Pryde <steve@stevepryde.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Selenium webdriver client for Rust, inspired by the python selenium library, and named after the atomic number for Selenium (Se)"
homepage = "https://github.com/stevepryde/thirtyfour"
repository = "https://github.com/stevepryde/thirtyfour"
readme = "README.md"
keywords = ["selenium", "webdriver", "testing", "test"]
categories = ["development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.0-alpha.2", features = ["blocking", "json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
log = "0.4"
urlparse = "0.7.3"
base64 = "0.11.0"
async-std = "1.2.0"
chrono = { version = "0.4", features = ["serde"] }
tokio = "0.2.0-alpha.6"

