[package]
name = "thirtyfour"
version = "0.3.4"
authors = ["Steve Pryde <steve@stevepryde.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = """
Thirtyfour is a W3C-compliant selenium webdriver client for Rust, inspired by the python selenium library,
and named after the atomic number for Selenium (Se).
"""
homepage = "https://github.com/stevepryde/thirtyfour"
repository = "https://github.com/stevepryde/thirtyfour"
readme = "README.md"
keywords = ["selenium", "webdriver", "chromedriver", "geckodriver", "automation"]
categories = ["api-bindings", "development-tools::testing"]

[dependencies]
reqwest = { version = "0.10.0", features = ["blocking", "json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
log = "0.4"
urlparse = "0.7.3"
base64 = "0.11.0"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "0.2", features = ["fs", "macros", "rt-threaded"] }
futures = "0.3"
