[package]
name = "thirtyfour"
version = "0.10.0-alpha.1"
authors = ["Steve Pryde <steve@stevepryde.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = """
Thirtyfour is a Selenium WebDriver library for Rust, for automated website UI testing.
It supports the full W3C WebDriver spec.
"""
homepage = "https://github.com/stevepryde/thirtyfour"
repository = "https://github.com/stevepryde/thirtyfour"
readme = "README.md"
keywords = ["selenium", "webdriver", "chromedriver", "geckodriver", "automation"]
categories = ["api-bindings", "development-tools::testing"]

[features]
default = ["tokio-runtime"]
tokio-runtime = ["tokio", "reqwest"]
async-std-runtime = ["async-std", "surf"]
blocking = ["tokio-runtime"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
tokio = { version = "0.2", features = ["fs", "macros", "rt-threaded", "io-util"], optional = true }
reqwest = { version = "0.10", features = ["blocking", "json"], optional = true }
async-std = { version = "1.5", optional = true }
surf = { version = "2.0.0-alpha.2", features = ["curl-client"], optional = true }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
log = "0.4"
urlparse = "0.7.3"
base64 = "0.11.0"
chrono = { version = "0.4", features = ["serde"] }

[[example]]
name = "async"
required-features = ["tokio-runtime"]

[[example]]
name = "sync"
required-features = ["blocking"]
