name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the test website
      run: docker-compose up -d --build
    - name: Check running containers
      run: docker ps -a
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features=blocking -- --test-threads=1
